import Head from 'next/head'
import useLocale from "@/components/hooks/locale";
import styles from "@/styles/button.module.css";

export default function Home() {
  const {t} = useLocale();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <div className='h-[2000px]'>
        <h1 className='text-lg'>{t.GREETING}</h1>

        {/*CSS Modulesを用いたデザインのサンプル*/}
        <div className={styles.button}>
          Styled Button with CSS Modules
        </div>
      </div>
    </>
  )
}
